<?php 
	$_code=$this->getMethodCode();
	$carrier = $this->getMethodInstance();
	$pickupData = $this->getQuote()->getPickupData();
	$_rate = $this->getRate();
	$optionsData = $this->getOptionsData();
	if(!isset($pickupData['store']))
	{
		$pickupData['store'] = -1;
	}
?>
<ul class="form-list" id="shipping_form_<?php echo $_rate->getCode() ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_store" class="required"><em>*</em><?php echo $this->__('Choose Store Location:') ?></label>
        <span class="input-box">
            <select class="required-entry" name="shipping_pickup[store]">
            	<option value='' <?php if($pickupData['store'] == ''){ echo "selected=selected";} ?>><?php echo $this->__('Select Store..');?></option>
                <?php
                foreach($optionsData as $options){
                    $option = "<option value=' " . $options . "''";
                    $option .= ($pickupData['store'] == 'Store1') ? "selected=selected>" : ">";
                    $option .= $options . "</option>";
                    echo $option;
                }
                ?>
            </select>
        </span>
    </li>
</ul>